import type { ConversationMessage } from '../types';

/**
 * How a message's header presents its `from`: the `userId`, else the
 * `kind`. A message with no `from` was generated by the harness, and the
 * label names what it is: "tool" when it carries a tool result, "system"
 * otherwise. The label belongs to the message, not to its blocks: one tool
 * result anywhere in it makes the whole message "tool".
 */
export function senderLabel(message: ConversationMessage): string {
  if (message.from) {
    return message.from.userId ?? message.from.kind;
  }
  return message.content.some((b) => b.type === 'tool_result') ? 'tool' : 'system';
}
