version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  - package-ecosystem: "cargo"
    directory: "/mvp"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directory: "/poc"
    schedule:
      interval: "weekly"
    groups:
      cargo:
        patterns:
          - "*"
